name: Build
on:
  push:
  pull_request:
  repository_dispatch:

env:
  NODE_VERSION: 20.x
jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    # only run if in main
    if: github.ref == 'refs/heads/main' && (github.event_name == 'repository_dispatch' || github.event_name == 'push')
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'

      - name: Restore pnpm cache
        uses: actions/cache@v4
        continue-on-error: true
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Install dependencies
        run: pnpm install

      - name: Publish
        # only publish if a direct `push`/`repository_dispatch`
        uses: cloudflare/wrangler-action@2.0.0
        if: github.event_name == 'repository_dispatch' || github.event_name == 'push'
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          command: deploy

        env:
          NODE_ENV: production
